lapordiri/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views

app_name = 'lapordiri'

urlpatterns = [
    path('', views.lapordiri_home, name='home'),
    path('lapor', views.lapordiri_lapor, name='lapor'),
    path('datatabel', views.lapordiri_datatabel, name='datatabel')
]

tk1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('lapordiri/', include('lapordiri.urls')),
    path('artikel/', include('artikel.urls')), 
    path('donasi/', include('Donasi.urls')),
    path('forum/', include('forum.urls'))
]

lapordiri/models.py
from django.db import models

# Create your models here.
class Laporan(models.Model):
    kota = models.TextField(max_length=300)
    jumlahPos = models.IntegerField(default=1)

    def __str__ (self):
        return self.kota

lapordiri/forms.py
from django import forms
from .models import Laporan

class LaporForm(forms.Form):
    nama = forms.CharField(label='Nama', max_length=100)
    telp = forms.CharField(label='Nomor Telefon', max_length=100)
    prov = forms.CharField(label='Provinsi', max_length=100)
    kota = forms.CharField(label='Kabupaten/Kota', max_length=100)

lapordiri/views.py
from django.shortcuts import render, redirect
from .forms import LaporForm
from .models import Laporan
from django.http.response import JsonResponse
from django.db.models import Sum
from django.contrib.auth.decorators import *
from django.core import serializers

context = {}
# Create your views here.
def lapordiri_home(request):
    context['laporan'] = Laporan.objects.all()
    return render(request, 'home.html', context)

def lapordiri_lapor(request):
    if request.method == "POST":
        form = LaporForm(request.POST)
        if form.is_valid():
            kota = form.cleaned_data.get('kota')
            lapor = Laporan.objects
            for laporans in lapor.all():
                if laporans.kota.lower() == kota.lower():
                    laporans.jumlahPos += 1
                    laporans.save()
                    return redirect('lapordiri:home')
            Laporan.objects.create(kota=kota.capitalize())
            return redirect('lapordiri:home')
    else:
        form = LaporForm()
    return render(request, 'lapor.html', {'form': form})

def lapordiri_datatabel(request):
    tabel = list(Laporan.objects.values())
    return JsonResponse(tabel, safe=False)

lapordiri/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Lapor Diri | Seputar Covid</title>
<link rel='stylesheet' type='text/css' href='{% static "lapordiri.css" %}'>
<link rel='stylesheet' type='text/css' href='{% static "main.css" %}'>
{% endblock meta %}

{% block content %}
<div class="container pb-5 pt-4">

    <div class="row1">
        <h1>Lapor Diri</h1>
    </div>

    <div class="row2" style="padding: 19px 0 19px 0;">
        <table class="table1">
            <tr>
                <th>
                    <div class="headleft">
                        Kota
                    </div>
                </th>
                <th>
                    <div class="headright">
                        Positif Covid
                    </div>
                </th>
            </tr>
            {% if laporan %}
                {% for lapor in laporan %}
                <tr>
                    <td>
                        <div class="theleft">
                            {{ lapor.kota }}
                        </div>
                    </td>
                    <td>
                        <div class="theright">
                            {{ lapor.jumlahPos}}
                        </div>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td>
                        <div class="theleft">
                            Masih
                        </div>
                    </td>
                    <td>
                        <div class="theright">
                            Kosong
                        </div>
                    </td>
                </tr>
            {% endif %}
        </table>
    </div>

    <div class="row3">
        <a class="button-fill" href='{% url "lapordiri:lapor" %}'> Lapor </a>
    </div>

</div>
{% endblock content %}

{% block extra_script %}
<script src= '{% static "tableupdate.js" %}' type="text/javascript"></script>
{% endblock extra_script %}

{% block script %}
{% endblock script %}

lapordiri/templates/lapor.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block meta %}
<title>Lapor Diri | Seputar Covid</title>
<link rel='stylesheet' type='text/css' href='{% static "lapordiri.css" %}'>
<link rel='stylesheet' type='text/css' href='{% static "main.css" %}'>
{% endblock meta %}

{% block content %}
<div class="container pb-5 pt-4">
    <div class="row1">
      <h1>Lapor Diri</h1>
    </div>
    
    <div class="row1 pt-5">
        <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
            {{ form|crispy }}
          </fieldset>
          <div class="row3 pt-5">
            <button class="button-fill" type="submit"> Lapor </button>
          </div>
        </form>
    </div>
  </div>
{% endblock content %}