artikel/urls.py
from django.urls import path 
from . import views

app_name = 'artikel'

urlpatterns = [
    path('', views.home, name="home"), 
    path('data/', views.home_data, name="home_data"), 
    path('add/', views.add, name="add"), 
    path('add/data/', views.add_data, name="add_data"), 
    path('details/<int:article_id>/', views.details, name="details"),
    path('details/<int:article_id>/data/', views.details_data, name="details_data"),
    path('delete/<int:article_id>/data/', views.delete_data, name="delete_data"),
    path('edit/<int:article_id>/', views.edit, name="edit"),
    path('edit/<int:article_id>/data/', views.edit_data, name="edit_data"),
]

tk1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('lapordiri/', include('lapordiri.urls')),
    path('artikel/', include('artikel.urls')), 
    path('donasi/', include('Donasi.urls')),
    path('forum/', include('forum.urls'))
]

artikel/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=180)
    img = models.URLField(max_length=300)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    time_posted = models.DateTimeField(auto_now_add=True, auto_now=False, blank=True)

    

artikel/forms.py
from django import forms 
from .models import Article 
from django.forms import widgets, TextInput, Textarea, DateTimeInput, FileInput

class ArticleForm(forms.ModelForm):
    class Meta :
        model = Article
        fields = ['title', 'img', 'content']
        widgets = {
            'title' : TextInput(attrs={'placeholder' : 'Nama', 'id' : 'data-title', 'required' : True}), 
            'img' : TextInput(attrs={'placeholder' : 'URL gambar', 'id' : 'data-img', 'required' : False}), 
            'content' : Textarea(attrs={'placeholder' : 'Konten', 'id' : 'data-content', 'required' : True}),
            'time_posted': DateTimeInput(format='%d/%m/%Y %H:%M', )
        }

artikel/views.py
from django.shortcuts import render, redirect 
from .models import Article
from main.models import Profile 
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
import datetime

def home(request):
    return render(request,"artikel/home.html")

def home_data(request):
    article = Article.objects.all()
    article_arr = []
    for a in article : 
        temp = {}
        temp['title'] = a.title
        temp['img'] = a.img
        temp['content'] = a.content
        temp['author'] = a.author.username
        temp['isTenagaMedis'] = a.author.profile.isTenagaMedis
        temp['id'] = a.id
        temp['time_posted'] = a.time_posted
        article_arr.append(temp)
    
    user = {}
    user['username'] = request.user.username

    context = {
        'article_arr' : article_arr,
        'user' : user,  
    }
    return JsonResponse(context)


def details(request, article_id):
    return render(request, 'artikel/details.html')

def details_data(request, article_id):
    obj = Article.objects.get(id=article_id)
    
    context = {}
    context['author'] = obj.author.username
    context['isTenagaMedis'] = obj.author.profile.isTenagaMedis
    context['title'] = obj.title
    context['img'] = obj.img
    context['content'] = obj.content
    context['time_posted'] = obj.time_posted
    
    return JsonResponse(context)

@login_required
def add(request):
    form = ArticleForm(request.POST)
    return render(request, 'artikel/add.html', {'form' : form, } )

def add_data(request): 
    if request.method == 'POST':
        data_title = request.POST.get('title')
        data_img = request.POST.get('img')
        data_content = request.POST.get('content')
        
        context = {}

        post = Article(title=data_title, img=data_img, content=data_content,author=request.user)
        post.save()

        context['title'] = post.title
        context['img'] = post.img 
        context['content'] = post.content
        context['author'] = post.author.username
        context['time'] = post.time_posted
 
        return JsonResponse(context)

def delete_data(request, article_id):
    obj = Article.objects.get(id=article_id)
    obj.delete()
    context = {'status' : 'success'}
    return JsonResponse(context)

@login_required
def edit(request, article_id):
    obj = Article.objects.get(id=article_id)
    form = ArticleForm(instance=obj)
    return render(request, 'artikel/edit.html', {'form': form,})
   
def edit_data(request, article_id):
    obj = Article.objects.get(id=article_id)
    context = {}
    if request.method == 'POST':
        data_title = request.POST.get('title')
        data_img = request.POST.get('img')
        data_content = request.POST.get('content')

        obj.title = data_title
        obj.img = data_img
        obj.content = data_content
        obj.save()
        
        context['title'] = obj.title
        context['img'] = obj.img
        context['content'] = obj.content

        return JsonResponse(context)

artikel/templates/artikel/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block meta %}
    <title>Tambah Artikel</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/artikel.css' %}">
{% endblock meta %}

{% block content %}
<div class="container pb-5">
  <div class="row1">
    <h1>Tambah Artikel</h1>
  </div>
  <div class="row4">
    <form method="POST" id="post-form">
      {% csrf_token %}
      <fieldset class="form-group" >
        {{ form|crispy }}
      </fieldset>
      <div class="row3">
        <button class="button-fill" type="submit" id="post-text"> Tambah </button>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

{% block extra_script %}
  <script src="{% static 'js/add.js' %}" ></script>
{% endblock extra_script %}

artikel/templates/artikel/details.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>{{obj.title}}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/artikel.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/details.css' %}">
{% endblock meta %}

{% block content %}

<div class="container pb-5">
    <div class="row1 text-center" >
        <h3 id="title"></h3>
        <p class="text-muted" id="time_posted"></p>
        <div class="row mx-auto" style="justify-content:center;" id="author"></div>
    </div>
    <div class="row2" id="img"></div>
    <div class="row3 text-justify">
      <p style="word-break:break-word;" id="content"><!--{{obj.content | linebreaksbr}}--></p>
    </div>
</div>

{% endblock content %}

{% block extra_script %}
  <script src="{% static 'js/details.js' %}" ></script>
{% endblock extra_script %}

artikel/templates/artikel/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block meta %}
    <title>Edit Artikel</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/artikel.css' %}">
{% endblock meta %}

{% block content %}
<div class="container pb-5">

    <div class="row1">
        <h1>Edit Artikel</h1>
  </div>
    <div class="row4">
        <form method="POST" id="post-form">
            {% csrf_token %}
            <fieldset class="form-group">
            {{ form|crispy }}
            </fieldset>
            <div class="row3">
            <button class="button-fill" type="submit" id="post-text"> Simpan </button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

{% block extra_script %}
  <script src="{% static 'js/edit.js' %}" ></script>
{% endblock extra_script %}

artikel/templates/artikel/home.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<title>Artikel</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/artikel.css' %}">
{% endblock meta %}

{% block content %}

<div class="container pb-5">
  <div class="row1">
    <h1>Artikel</h1>
    <a class="btn btn-primary" href="{% url 'artikel:add' %}" role="button">+ Tambah Artikel</a>
    <br>
  </div>
  <br>

<div id="result">
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/artikel.js' %}" ></script>

{% endblock content %}