artikel/urls.py
from django.urls import path 
from . import views

app_name = 'artikel'

urlpatterns = [
    path('', views.home, name="home"), 
    path('data/', views.home_data, name="home_data"), 
    path('add/', views.add, name="add"), 
    path('add/data/', views.add_data, name="add_data"), 
    path('details/<int:article_id>/', views.details, name="details"),
    path('details/<int:article_id>/data/', views.details_data, name="details_data"),
    path('delete/<int:article_id>/data/', views.delete_data, name="delete_data"),
    path('edit/<int:article_id>/', views.edit, name="edit"),
    path('edit/<int:article_id>/data/', views.edit_data, name="edit_data"),
]

lapordiri/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views

app_name = 'lapordiri'

urlpatterns = [
    path('', views.lapordiri_home, name='home'),
    path('lapor', views.lapordiri_lapor, name='lapor'),
    path('datatabel', views.lapordiri_datatabel, name='datatabel')
]

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/',views.register, name='register'),
    path('login/',views.login_view, name='login'),
    path('logout/',views.logout_view, name='logout'),
    path('validate_username/', views.validate_username, name = "validate_username"),
    path('validate_password/', views.passwordValidation, name = "validate_password"),
    path('validate_email/', views.email_validation, name = "validate_email")
]

tk1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('lapordiri/', include('lapordiri.urls')),
    path('artikel/', include('artikel.urls')), 
    path('donasi/', include('Donasi.urls')),
    path('forum/', include('forum.urls'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="mb-4 navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand ml-3" href="{% url 'main:home' %}">SeputarCOVID</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText1" aria-controls="navbarText1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText1">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-3">
                <a class="nav-link waves-effect waves-light" href="{% url 'artikel:home' %}">Artikel <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item mr-3">
                <a class="nav-link waves-effect waves-light" href="/forum">Konsultasi</a>
            </li>
            <li class="nav-item mr-3">
                <a class="nav-link waves-effect waves-light" href="{% url 'lapordiri:home' %}">Lapor Diri</a>
            </li>
            <li class="nav-item mr-3">
              <a class="nav-link waves-effect waves-light" href="/donasi">Beri Donasi</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item mr-3">
                <a class="nav-link waves-effect waves-light" href="{% url 'main:logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item mr-3">
                <a class="nav-link waves-effect waves-light" href="{% url 'main:login' %}">Login</a>
              </li>
            {% endif %}

        </ul>
    </div>
  </nav>
   <!-- navbar provided by https://bootsnipp.com/snippets/lVrVa -->


  {% block content %}
  {% endblock content %}

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.4.1/js/mdb.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  {% block extra_script %}
  {% endblock extra_script %}

</body>
  {% block script %}
  {% endblock script %}
</html>